# ============================================================
# Neural Forge — plugins/examples/daily_digest.py
# Generates a daily Obsidian note at midnight with:
# - Tasks completed today
# - XP earned + level progress
# - SR review summary
# - Sleep log if available
# ============================================================

from plugins.base import BasePlugin, PluginManifest
from datetime import date


class DailyDigestPlugin(BasePlugin):
    manifest = PluginManifest(
        id          = "daily-digest",
        name        = "Daily Digest",
        version     = "1.0.0",
        description = "Generates a daily review note in your Obsidian vault at midnight.",
        author      = "neural-forge-team",
        hooks       = ["on_daily_reset"],
    )

    async def on_daily_reset(self, payload: dict) -> None:
        from db import get_db
        db     = await get_db()
        today  = date.today().isoformat()
        yesterday = str(date.today().replace(day=date.today().day - 1))

        # Gather stats for yesterday
        async with db.execute(
            "SELECT COUNT(*) as n FROM tasks WHERE user_id='default' AND done=1 AND done_at>=? AND done_at<?",
            (yesterday, today)
        ) as cur:
            tasks_done = (await cur.fetchone())["n"]

        async with db.execute(
            "SELECT SUM(xp) as xp FROM activity_log WHERE user_id='default' AND created_at>=? AND created_at<?",
            (yesterday, today)
        ) as cur:
            xp_row  = await cur.fetchone()
            xp_yesterday = int(xp_row["xp"] or 0)

        async with db.execute(
            "SELECT xp, level FROM users WHERE id='default'"
        ) as cur:
            user = await cur.fetchone()

        async with db.execute(
            """SELECT COUNT(*) as n, AVG(quality) as avg_q
               FROM sr_reviews WHERE user_id='default' AND reviewed_at>=? AND reviewed_at<?""",
            (yesterday, today)
        ) as cur:
            sr_row = await cur.fetchone()

        async with db.execute(
            "SELECT hours, quality, energy FROM sleep_logs WHERE user_id='default' AND log_date=?",
            (yesterday,)
        ) as cur:
            sleep = await cur.fetchone()

        # Build note content
        sleep_str = ""
        if sleep:
            sleep_str = f"\n## 🌙 Sleep\n- Hours: {sleep['hours']}h  \n- Quality: {sleep['quality']}/5  \n- Energy: {sleep['energy']}/10\n"

        sr_str = ""
        if sr_row and sr_row["n"] > 0:
            sr_str = f"\n## 🧠 Spaced Repetition\n- Reviews: {sr_row['n']}  \n- Avg Quality: {round(sr_row['avg_q'] or 0, 1)}/5\n"

        content = f"""---
tags: [daily-note, neural-forge]
date: {yesterday}
xp: {xp_yesterday}
---

# 📅 Daily Review — {yesterday}

## 📊 Summary
- **XP earned:** +{xp_yesterday}
- **Total level:** {user['level'] if user else '?'} ({user['xp'] if user else '?'} XP total)
- **Tasks completed:** {tasks_done}
{sleep_str}{sr_str}
## 🎯 Reflection
> _(Add your reflection here)_

---
*Generated by Neural Forge Daily Digest plugin*
"""
        note_path = f"NeuralForge/Daily/{yesterday}.md"
        await self.write_vault_note(note_path, content)
